// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClcHfaso9I-Sn3ZCccqZcaWD884ErEw7E',
    appId: '1:40088963588:web:ff7bebd93f2be08ccc0351',
    messagingSenderId: '40088963588',
    projectId: 'instagram-clone-4e56f',
    authDomain: 'instagram-clone-4e56f.firebaseapp.com',
    storageBucket: 'instagram-clone-4e56f.firebasestorage.app',
    measurementId: 'G-8DPK0EP3G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6cz42ks2A3KmxMUwNQQQtP_kPb-mQT7s',
    appId: '1:40088963588:android:a023b7c3a3a49d66cc0351',
    messagingSenderId: '40088963588',
    projectId: 'instagram-clone-4e56f',
    storageBucket: 'instagram-clone-4e56f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd4wA73kjGV4MIWTwgMKDybzFLuKQP-FY',
    appId: '1:40088963588:ios:7b7c46bd6713537bcc0351',
    messagingSenderId: '40088963588',
    projectId: 'instagram-clone-4e56f',
    storageBucket: 'instagram-clone-4e56f.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd4wA73kjGV4MIWTwgMKDybzFLuKQP-FY',
    appId: '1:40088963588:ios:7b7c46bd6713537bcc0351',
    messagingSenderId: '40088963588',
    projectId: 'instagram-clone-4e56f',
    storageBucket: 'instagram-clone-4e56f.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClcHfaso9I-Sn3ZCccqZcaWD884ErEw7E',
    appId: '1:40088963588:web:3fe3e0c162f7ebaacc0351',
    messagingSenderId: '40088963588',
    projectId: 'instagram-clone-4e56f',
    authDomain: 'instagram-clone-4e56f.firebaseapp.com',
    storageBucket: 'instagram-clone-4e56f.firebasestorage.app',
    measurementId: 'G-7QV4KFELSJ',
  );
}
